services:
  mysql:
    image: mysql:8.4
    container_name: loan-calculator-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: loan_calculator
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d

  app:
    build: .
    container_name: loan-calculator-app
    depends_on:
      - mysql
    ports:
      - "8088:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/loan_calculator
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_DATASOURCE_HIKARI_INITIALIZATION_FAIL_TIMEOUT: 0
volumes:
  mysql_data:
